# Global
safe:									true
exclude:							[TODO.md, REPOSITORY.md, CNAME, Gemfile, Gemfile.lock, __tests__]
include:							[_pages, _apps, _others, _extras, _scripts]
timezone:							Europe/London

# Dependencies | kramdown
markdown:							kramdown
  
# Styling
sass:
  sass_dir:						_sass
  load_paths:
                      - _sass
                      - _sass/bootstrap
                      - _sass/material
                      - _sass/custom
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all
  startings:					[]
  endings:            []
  artifacts:          [" /* */ ", " /* */", "/* */ ", "/* */", "/*jshint ignore:start*/", "/*jshint ignore:end*/"]
  ignore:
    envs:             [debug]

# Permalinks
permalink:						pretty

# Setup
title:                "Shelf Dog"
url:									shelf.dog
baseurl:							/
author:
  name:								"Shelf.dog"
  url:								https://github.com/shelf-dog

# Collections
collections:
  apps:
    output: true

# Collection Defaults
defaults:
  - scope:
      path: ""
      type: tests
    values:
      sitemap:
        exclude: true
        
# Custom variables
version:							"0.1.0"
launched:							"2017"
fonts:								"Anonymous+Pro:400|Inconsolata:400|Roboto:400,700|Roboto+Mono:400|Fira+Mono:400|Space+Mono:400"
debug:                "debug"
performance:          "perf"
compress:             "compress"
array:                []
highlight:            "fef513"
icon:                 "data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABILAAASCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACh+v8ApPz/Aons/wl23f0Det/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACV8PwA/f//AXPP8WF00fO+gd37e4Xg/giD3fwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AebvsAILF7zBOeNTiPWnL/2S05fWQ5P5QjeD8AIre/AAAAAAAAAAAAAAAAAAI/P4AE/b+ABP8/xoR2eZgBoGbFP///wFnj9mVTSfB/0gZvf88Z8T/e83tosX//wOB3/4AAAAAAAAAAAAAAAAAE/b+ABL2/hIV9v+lF+f0/Q6nvmOk5fxMT3vG7DASmf8yC5f/IC+W/0ydy+Wc6f4slOL8AAAAAAAAAAAAAAAAABL2/gwV9f6YGfT//hvl9f8xscyppuf92JrG6f9AOpP/PzaS/z1QkP87hLf/pN/0bQB8liQItcZiC/f8CAv0+gAW9P5EGfP+8CDy//8bz+X6V73d257l/v2a1Oz/j7nY/7Ha8P+v4/f/aq3V/3281rsStcm5D+/38w36/0sO+P4AHPL+Zx/w/vsl7f3/Hrva+F/N8vZ2xOP/IFmH/xxdlv+Bvt3/qOr//43R7P9xvNjwGcre9xX3//8Q9/6+D/j+FiHv/jMm7v7iJ+L3/yGw2PlY0/v8WLzl/xRhpf8CR4r/U5rF/5Di/f+P4Pz/cdDw9RvO5fga9P//FfX+9xL2/lYV9f0CLuv+hybT8P8ir9zzQ7jg/FO/5f9nyPn/Wbfw/3TR+P9e1Pv/aNn//1zQ9vQh1Oz1H/H//xrz/v0X9P5tOOT8AD/t/xoXu+XIH7Lj+Uu12/w7qdD/Ztn+/27d//9g0PX/T7zi/13Q9/9Vz/b2Jdbw+CTv/v8f8P7mG/L+OEDZ+gAAqOQAAazkgQ6y6P9Z1Pz+Ytj+/2TY//9m2v//T8Xt/y6Rtv9It97/Q8fx8CbV8vsq7P7/Je39mBzy/wUAAAAAArTwAAKz7zUDtvLWQs37/Wja//9m2f//Ztn//2TY//9i2P//Y9j+/Si76/Mx1PX9M+j9wSnr/SEr6v0AAAAAAAK8+gADvPkBALn5IkDO/WZm2f/NZtn//mbZ//9m2f//Ztn//0HM+v8Kte71Msv1gEbm/hpU1voAM+b9AAAAAAAAAAAAAAAAAGbZ/wBm2f8AZtn/HGbZ/2Rm2f+SZ9n/oVXU/qYQv/mzALn2cQO38wgCt/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm2f8AZtn/AHLf/wEZtPsCAbv+BgLJ/wECx/8AAAAAAAAAAAAAAAAA/j8AAPwfAAD8HwAAwA8AAIAJAAAAAQAAAAEAAAAAAAAAAAAAAAAAAIAAAADAAAAAwAEAAMADAAD4BwAA/g8AAA=="

# Extras
analytics:
  enable:							false
  id:									"UA-53673057-8"
  
app:
  content:            content
  namespace:          shelf_dog
  tests:              _tests
  stripe:
    live:             pk_live_51HTNxjLM8piW21zC3g9dIqv8PiZ3joimbNx83XRkMQ8nx6JFKfEHYRWgbO1DYyHwL0mfCJbeOL5ZtZvWQyUH750M00LIMgyNuL
    testing:          pk_test_51HTNxjLM8piW21zC8cAAzOsUMpkuMuc2UoybVhsj2C7ObwCIvg8u89NgteIAXpKsWDgqf7h9ZSSpiOB89LXk44AG00Esxs4XB9